"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: adam_u.msg.dds_
  IDL file: LowState_.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
# import adam_u


@dataclass
@annotate.final
@annotate.autoid("sequential")
class LowState_(idl.IdlStruct, typename="adam_u.msg.dds_.LowState_"):
    motor_state: types.array['pndbotics_sdk_py.idl.adam_u.msg.dds_.MotorState_', 19]
    reserve: types.uint32


